version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "13000:3000"
    volumes:
      - .:/api
      - hidden-volumes:/api/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
    networks:
      - api-network
    tty: true

  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgressql/data

volumes:
  db-data:
  hidden-volumes:

networks:
  api-network: