version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - '${API_PORT:-80}:80'
      - '7447:7447'
    volumes:
      - .:/api
      - hidden-data:/api/node_modules
    env_file:
      - .env.dev
    depends_on:
      - db
    networks:
      - api-network
    tty: true

  db:
    image: mysql:8.0
    env_file:
      - .env.dev
    ports:
      - '${DB_PORT:-3306}:3306'
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  db-data:
  hidden-data:

networks:
  api-network:
