version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
    ports:
      - '${API_PORT:-80}:80'
    volumes:
      - .:/api
      - hidden-data:/api/node_modules
    env_file:
      - .env.dev
    depends_on:
      - db
    tty: true

  db:
    image: mysql:8.0
    env_file:
      - .env.dev
    ports:
      - '${DB_PORT:-3306}:3306'
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  db-data:
  hidden-data:
