# prisma使用時、"Segmentation fault"が発生するため、あえてnode:16にしている
FROM node:16-slim

RUN apt-get update \
    && apt-get install -y openssl

WORKDIR /api

COPY package.json .
COPY yarn.lock .

RUN yarn install --frozen-lockfile

RUN yarn global add @nestjs/cli

COPY src/adaptor/primary/rdbms/prisma /api/src/adaptor/primary/rdbms/prisma
RUN yarn prisma:generate

ENV NODE_ENV=development